### ISSUE TITLE
Database Modelling and Relational Design Structure

### ISSUE THREAD

**Issue by Josconic** [BuildForSDG/CODE-OF-HONOUR#5]
1. User fields
2. Relational Database Design, and Mapping connection

**Comment by Abubakarharuna10** [comment]
I will work on the database for now

**Comment by sam-karis** [comment]
Hi @Abubakarharuna10 can you attach a database `ER diagram` on this issue I would like to see the relation between different tables. The diagram does not need to be complex it can be just a simple representation of data tables and how they relate with each other. You can brainstorm as a team on this.
Here is an example of `ER diagram`
![image](https://user-images.githubusercontent.com/22454909/81615829-fa592d00-93ea-11ea-8686-0a3157eda428.png)

**Comment by Josconic** [comment]
I have designed the User fields
![CODE OF HONOUR MAPPING DESIGN-Page-7 (1)](https://user-images.githubusercontent.com/12628617/81646472-2f817180-9423-11ea-9d1f-3d47e63e34b9.jpg)

**Comment by Cyber-Lord** [comment]
I have added the database on a new branch called backend. Kindly go through it pls

**Comment by sam-karis** [comment]
I would suggest normalizing the database structure to avoid duplications. Please look at this link and see if you can identify areas you need to improve https://www.studytonight.com/dbms/database-normalization.php.

After going through the doc and brainstorming with the team on area you can improve. We can sync and go through it together

**Comment by sam-karis** [comment]
> I have added the database on a new branch called backend. Kindly go through it pls

Please ensure you do not push code not needed like `__pycache__` utilize `.gitignore`
